name = "SAML"
uuid = "12345678-1234-5678-1234-567812345678"
authors = ["Your Name <your.email@example.com>"]
version = "0.1.0"

[deps]
LightXML = "9c8b4983-aa76-5fa4-0cda-b378efa6078b"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
SHA = "ea8e919c-243c-51af-933b-eaad308212d7"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1abc00a3edb"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
UUIDs = "550dbc7b-8242-5cf5-8194-8f1ae97477f9"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f2afa"

[targets]
test = ["Test"]
